services:
  mysql:
    container_name: phpfun_sql
    image: mariadb:10.8.2
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Budapest
    networks:
      inner:
        aliases:
          - mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpfun_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PMA_PORT}:80
    networks:
      inner:
        aliases:
          - pma
    depends_on:
      - mysql
  app:
    container_name: phpfun_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../app/:/var/www/html
      - ./phpfun.conf:/etc/apache2/sites-enabled/phpfun.conf
    ports:
      - "${APP_PORT}:8000"
    networks:
      inner:
        aliases:
          - phpfun_app
    depends_on:
      - mysql
networks:
  inner:
    driver: bridge

volumes:
  db_data: {}
